In [1]:
import tensorflow as tf
sess = tf.Session()

# Prepare data

In [3]:
# 'logits' is the output of the model, 'labels' is the one-hot ground truth of samples
logits = tf.constant([[5., 2., 2.], [10., 5., 5.], [9., 1., 2.], [7., 7., 1.]], name='logits')
labels = tf.constant([[1., 0., 0.], [0., 1., 0.], [0., 0., 1.], [1., 0., 0.]], name='labels')
predictions = tf.nn.softmax(logits, name='prediction')
print("Softmax = {}".format(sess.run(predictions)))

distribution = tf.reduce_sum(labels, axis=0)
print("Sample distribution = {}".format(sess.run(distribution)))

Softmax = [[  9.09443021e-01   4.52785008e-02   4.52785008e-02]
 [  9.86703277e-01   6.64835423e-03   6.64835423e-03]
 [  9.98754263e-01   3.35044722e-04   9.10745992e-04]
 [  4.99381065e-01   4.99381065e-01   1.23784191e-03]]
Sample distribution = [ 2.  1.  1.]


# Comparison betweent different loss

In [5]:
def my_cross_entropy(predictions, labels):
    print("\nCross Entropy implementation:")
    loss = -labels * tf.log(predictions)
#     print(sess.run(loss))
    loss = tf.reduce_sum(loss, axis=1)
    print(sess.run(loss))
    loss = tf.reduce_mean(loss)
    print("My cross entropy loss = {}".format(sess.run(loss)))
    return loss

def focal_loss(predictions, labels, distribution):
    print("\nFocal loss implementation:")
    gamma = 2
    alpha = 1 - distribution / (tf.reduce_sum(distribution))
    print("gamma = {}\nalpha = {}".format(gamma, sess.run(alpha)))
    focalLoss = -labels * alpha * tf.pow(1 - predictions, gamma) * tf.log(predictions)
#     print(sess.run(focalLoss))
    focalLoss = tf.reduce_sum(focalLoss, axis=1)
    print(sess.run(focalLoss))
    focalLoss = tf.reduce_mean(focalLoss)
    print("Focal loss = {}".format(sess.run(focalLoss)))
    return focalLoss

def tf_cross_entropy(logits, labels):
    print("\nCross entropy by tensorflow:")
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels)
    print(sess.run(loss))
    loss = tf.reduce_mean(loss)
    print("Tensorflow cross entropy loss = {}".format(sess.run(loss)))
    return loss
    
ceLoss = my_cross_entropy(predictions, labels)
tfLoss = tf_cross_entropy(logits, labels)
focalLoss = focal_loss(predictions, labels, distribution)


Cross Entropy implementation:
[ 0.09492294  5.01338577  7.00124645  0.69438583]
My cross entropy loss = 3.2009854316711426

Cross entropy by tensorflow:
[ 0.09492292  5.01338577  7.00124645  0.69438583]
Tensorflow cross entropy loss = 3.2009854316711426

Focal loss implementation:
gamma = 2
alpha = [ 0.5   0.75  0.75]
[  3.89210909e-04   3.71020937e+00   5.24137449e+00   8.70132521e-02]
Focal loss = 2.259746551513672
